name: Deploy to Firebase Cloud Functions

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_and_deploy_functions:
    runs-on: ubuntu-latest
    environment: ${{ github.event_name == 'push' && 'PRODUCTION' || 'STAGING' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Install Dependencies
        run: |
          yarn --immutable
      - name: Install Firebase CLI
        run: npm install -g firebase-tools@latest
      - name: Authenticate with Firebase
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > service-account.json
      - name: Deploy Firebase functions & Firestore rules & indexes
        run: |
          firebase functions:config:set --non-interactive \
            config.chromewebstorelink="$EXTENSION_LINK" \
            config.chatgptapikey="$CHATGPT_API_KEY" \
            config.mailgunapikey="$MAILGUN_API_KEY" \
            config.sentrydsn="$SENTRY_DSN" \
            config.domain="$DOMAIN" \
            database.url=$FIREBASE_DATABASE_URL \
            project.id="$FIREBASE_PROJECT_ID" --project $FIREBASE_PROJECT_ID

          yarn deploy:all --non-interactive --force &&
          yarn seeder start
        working-directory: packages/engine
        env:
          DOMAIN: ${{ vars.DOMAIN }}
          EXTENSION_LINK: ${{ vars.EXTENSION_LINK }}
          FIREBASE_PROJECT_ID: ${{ vars.FIREBASE_PROJECT_ID }}
          FIREBASE_DATABASE_URL: ${{ vars.FIREBASE_DATABASE_URL }}

          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          CHATGPT_API_KEY: ${{ secrets.CHATGPT_API_KEY }}
          MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}

          GOOGLE_APPLICATION_CREDENTIALS: '${{ github.workspace }}/service-account.json'
      - name: Seed initial data
        run: |
          yarn start
        working-directory: packages/seeder
        env:
          FIREBASE_PROJECT_ID: ${{ vars.FIREBASE_PROJECT_ID }}
          GOOGLE_APPLICATION_CREDENTIALS: '${{ github.workspace }}/service-account.json'
