name: Deploy to Firebase Cloud Functions on merge

'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy_functions:
    name: Build and Deploy Cloud Functions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Install Dependencies
        run: |
          yarn --immutable
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Authenticate with Firebase
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_RECAP_381618 }}" > service-account.json
      - name: Deploy Firebase functions, Firestore rules, and indexes
        run: |
          firebase functions:config:set config.chatgptapikey="$CHATGPT_API_KEY" config.mailgunapikey="$MAILGUN_API_KEY" config.domain="$DOMAIN" private.key="$FIREBASE_PRIVATE_KEY" project.id="$FIREBASE_PROJECT_ID" client.email="$FIREBASE_EMAIL" --project $FIREBASE_PROJECT_ID
          yarn workspace @recap/engine deploy:all
        env:
          CHATGPT_API_KEY: ${{ secrets.CHATGPT_API_KEY }}
          MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
          DOMAIN: ${{ secrets.DOMAIN }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_FIRESTORE_ACCOUNT_PRIVATE_KEY }}
          FIREBASE_EMAIL: ${{ secrets.FIREBASE_FIRESTORE_ACCOUNT_EMAIL }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          GOOGLE_APPLICATION_CREDENTIALS: '${{ github.workspace }}/service-account.json'
