name: Deploy to Firebase Cloud Functions on merge
on:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  build_and_deploy_functions:
    name: Build and Deploy Cloud Functions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Install Dependencies
        run: |
          yarn --immutable
      - name: Install Firebase CLI
        run: npm install -g firebase-tools@latest
      - name: Authenticate with Firebase
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > service-account.json
      - name: Deploy Firebase functions, Firestore rules, and indexes
        run: |
          firebase functions:config:set --non-interactive config.chromewebstorelink="$EXTENSION_LINK" config.chatgptapikey="$CHATGPT_API_KEY" config.mailgunapikey="$MAILGUN_API_KEY" config.sentrydsn="$SENTRY_DSN" config.domain="$DOMAIN" project.id="$FIREBASE_PROJECT_ID" --project $FIREBASE_PROJECT_ID
          yarn deploy:all --non-interactive --force
        working-directory: packages/engine
        env:
          DOMAIN: ${{ secrets.DOMAIN }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          EXTENSION_LINK: ${{ secrets.EXTENSION_LINK }}
          CHATGPT_API_KEY: ${{ secrets.CHATGPT_API_KEY }}
          MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          GOOGLE_APPLICATION_CREDENTIALS: '${{ github.workspace }}/service-account.json'
      - name: Seed initial data
        run: |
          yarn seeder start
