name: Deploy to Firebase Cloud Functions on merge

'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy_functions:
    name: Build and Deploy Cloud Functions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Install Dependencies
        run: |
          yarn --immutable
      - name: Create env file
        run: |
          echo "FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}" > .env.production
          echo "FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN }}" >> .env.production
          echo "FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}" >> .env.production
          echo "FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }}" >> .env.production
          echo "FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}" >> .env.production
          echo "FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }}" >> .env.production
          echo "FIREBASE_MEASUREMENT_ID=${{ secrets.FIREBASE_MEASUREMENT_ID }}" >> .env.production
      - name: Build
        run: yarn workspace @recap/app build
      - name: Deploy Firebase functions, Firestore rules, and indexes
        run: |
          firebase functions:config:set config.chatgptapikey="$CHATGPT_API_KEY" config.mailgunapikey="$MAILGUN_API_KEY" config.domain="$DOMAIN" private.key="$FIREBASE_PRIVATE_KEY" project.id="$FIREBASE_PROJECT_ID" client.email="$FIREBASE_EMAIL" --project $FIREBASE_PROJECT_ID
          yarn workspace @recap/engine deploy:all
        env:
          CHATGPT_API_KEY: ${{ secrets.CHATGPT_API_KEY }}
          MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
          DOMAIN: ${{ secrets.DOMAIN }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_FIRESTORE_ACCOUNT_PRIVATE_KEY }}
          FIREBASE_EMAIL: ${{ secrets.FIREBASE_FIRESTORE_ACCOUNT_EMAIL }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
