name: Release new production version
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Production Release
    runs-on: ubuntu-latest
    environment: PRODUCTION

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Install Dependencies
        run: |
          yarn --immutable
      - name: Create env file
        run: |
          echo "DOMAIN=${{ vars.DOMAIN }}" > .env
          echo "OAUTH2_CLIENT_ID=${{ vars.OAUTH2_CLIENT_ID }}" >> .env
          echo "FIREBASE_APP_ID=${{ vars.FIREBASE_APP_ID }}" >> .env
          echo "FIREBASE_PROJECT_ID=${{ vars.FIREBASE_PROJECT_ID }}" >> .env
          echo "FIREBASE_AUTH_DOMAIN=${{ vars.FIREBASE_AUTH_DOMAIN }}" >> .env
          echo "FIREBASE_STORAGE_BUCKET=${{ vars.FIREBASE_STORAGE_BUCKET }}" >> .env
          echo "FIREBASE_MEASUREMENT_ID=${{ vars.FIREBASE_MEASUREMENT_ID }}" >> .env
          echo "FIREBASE_MESSAGING_SENDER_ID=${{ vars.FIREBASE_MESSAGING_SENDER_ID }}" >> .env

          echo "SENTRY_DSN=${{ secrets.SENTRY_DSN }}" >> .env
          echo "EXTENSION_KEY=${{ secrets.EXTENSION_KEY }}" >> .env
          echo "FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}" >> .env
      - name: Build
        working-directory: ./packages/extension
        run: |
          yarn build
          yarn package
      - name: Get version from package.json
        id: get_version
        run: echo "version=v$(node -p -e "require('./package.json').version")" >> $GITHUB_ENV
      - name: Check version
        uses: mukunku/tag-exists-action@v1.2.0
        id: check_version
        with:
          tag: ${{ env.version }}
      - name: Release
        if: steps.check_version.outputs.exists != 'true'
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.version }}
          draft: false
          prerelease: false
      - name: Upload release asset
        if: steps.check_version.outputs.exists != 'true'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./packages/extension/dist.zip
          asset_name: recap-${{ env.version }}.zip
          asset_content_type: application/zip
